# Generated by Django 3.2.13 on 2022-12-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_participant_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='participant',
            field=models.ManyToManyField(to='projects.Participant'),
        ),
    ]
