# Generated by Django 3.2.13 on 2022-12-10 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20221210_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='participant',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
