# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.17.1'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    #- run: cd pjt_front_react && npm install
    #- run: cd pjt_front_react && npm run build
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_TEST_X_HOST }}
        username: ${{ secrets.AWS_TEST_X_USERNAME }}
        key: ${{ secrets.AWS_TEST_X_KEY }}
        port: ${{ secrets.AWS_TEST_X_PORT }}
        script_stop: true
        script: |
          ls

